# Generated by Django 3.0.3 on 2020-06-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200602_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following_profiles',
            field=models.ManyToManyField(blank=True, related_name='_profile_following_profiles_+', to='profiles.Profile'),
        ),
    ]
